changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title: "Breaking Changes"
      labels:
        - breaking
        - breaking-change

    - title: "New Features"
      labels:
        - feature
        - enhancement

    - title: "Bug Fixes"
      labels:
        - bug
        - fix
        - bugfix

    - title: "Documentation"
      labels:
        - documentation
        - docs

    - title: "Maintenance"
      labels:
        - chore
        - maintenance
        - dependencies
        - deps

    - title: "Other Changes"
      labels:
        - "*"
